[build]
    functions = "netlify/functions"

[[redirects]]
  from = "/api/campgrounds/*"
  to = "/.netlify/functions/campflareProxy/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}